AWSTemplateFormatVersion: '2010-09-09'
Description: Terraform Automation Role

Resources:

  TerraformExecutionRole:
    Type: AWS::IAM::Role

    Properties:

      RoleName: TerraformExecutionRole

      AssumeRolePolicyDocument:
        Version: '2012-10-17'

        Statement:
          - Effect: Allow

            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root

            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

Outputs:

  RoleArn:
    Value: !GetAtt TerraformExecutionRole.Arn
